### ISSUE TITLE
Full RHEL6 / CentOS6 support

### ISSUE THREAD

**Issue by ktaraszk** [lxcenter/hypervm#42]
Currently both Xen and OpenVZ support doesn't work for current development version of hypervm. Supporting of RHEL6 / CentOS6 is required for new release of hypervm

**Comment by dterweij** [comment]
Keep in mind that stable is not always the newest. CentOS 5 is still not EOL and is supported.
But yes, HyperVM should run in CentOS 5 and CentOS 6 and support both Xen and OpenVZ with any difference between CentOS 5-6 versions of Xen and OpenVZ.

Thank you.

**Comment by semirke** [comment]
OpenVZ mostly works, but some variables needs reviewing (vswap related), also the 64bit "unlimited" long_max should be changed. 
Im doing that.

**Comment by dterweij** [comment]
The Dev runs fine on C6. Test and report bugs.

**Comment by kdkaushik** [comment]
Could not access hypervm web panel when i installed it on Centos 6.5 minimal

**Comment by semirke** [comment]
Hi, 
 supplied informatin is insufficient for any kind of support. 
 Please try to find answer for your problem at LxCenter forums (old knowledgebase: forum.lxcenter.org; new community forum: community.lxcenter.org)

Bests,
Semir
