### ISSUE TITLE
Does hypervm has more features and functionalities compare to solusvm?

### ISSUE THREAD

**Issue by topstarnetwork** [lxcenter/hypervm#89]
Does hypervm has more features and functionalities compare to solusvm?
I am looking for the best open source stable vps managment software with future upgrade and same features as http://solusvm.com/

**Comment by dkstiler** [comment]
Hello topstarnetwork !! For your questions we have a forum that every member can ask whatever they like take a look at:
http://community.lxcenter.org/index.php
As for the hypercm vs solusvm we have one of the most popular open source vps managing panel
From my experience the stable release that currently supports centos 5 for xen and openz virtualizors, and seems very decent

Also we are developing further to support centos 6 and some new features, as for updates we will have new features added if we have more developers around if you are interested look at http://community.lxcenter.org/index.php/topic,449.msg1792.html#new

If you have any more questions please feel free to post and ask at our forums :)

**Comment by topstarnetwork** [comment]
Just a littel more question, Does hypervm has client vps control panel from where they can login and manage theire own vps?
I see you have a whmcs billing plugin but don't see any hostbillap one.
Do you have any hostbillap extension as I am not using whmcs software?
Regards, Heather

**Comment by dkstiler** [comment]
Hello again, Please i would notice that any further questions i would like to be asked at the community forum.
As for client panel yes of course hypervm is a fully functional hosting panel, for now most billing extensions have been made by the billing software so better look at them if they have made one, from a short search seems that hostbillap has one look there http://wiki.hostbillapp.com/index.php?title=HyperVM
