### ISSUE TITLE
Lxcenter.org not available

### ISSUE THREAD

**Issue by slrslr** [lxcenter/hypervm#96]
Hello,

installation instructions are not mentioned here, but instead im linked to lxcenter.org site which seems  to not be working.
How to install HyperVM and what are requirements please?

Thank You

**Comment by dterweij** [comment]
DNS servers are down. No installation possible.

**Comment by ktaraszk** [comment]
use http://hypervm-ng.org instead if you like to install HypeVM. lxcenter.org seems to be dead :(

**Comment by slrslr** [comment]
I can not access hypervm-ng.org (timeout)

**Comment by lxcenterorg** [comment]
You'd have to change your hosts file and point "download.lxcenter.org" to
the IP address 75.98.169.138 .

**Comment by slrslr** [comment]
Thank you so much!

> echo "75.98.169.138 download.lxcenter.org" >> /etc/hosts

it worked. I am willing to host this repo if you are interested. Why not mirror
