### ISSUE TITLE
What URL should i use instead of download.lxcenter.org/download/ ?

### ISSUE THREAD

**Issue by slrslr** [lxcenter/hypervm#98]
HyperVm installation (hypervm-install-master.sh) obviously can not connect offline server of the lxcenter.org:

> Installing packages which lxlighttpd zip unzip hypervm-core-php curl yum-plugin-replace mysql mysql-server...
> Loaded plugins: fastestmirror
> Setting up Install Process
> Loading mirror speeds from cached hostfile
>  * base: mirror.23media.com
>  * epel: mirrors.aliyun.com
>  * extras: mirror.wiuwiu.de
>  * soluslabs: repo-france-rbx.solusvm.com
>  * updates: mirror.checkdomain.de
> http://download.lxcenter.org/download/update/centos-6/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'download.lxcenter.org'"
> Trying other mirror.
> Error: Cannot retrieve repository metadata (repomd.xml) for repository: lxcenter-updates. Please verify its path and try again

Please which URL i should be using instead or how do i setup own repository? Thank you

**Comment by lxcenterorg** [comment]
You'd have to change your hosts file and point "download.lxcenter.org" to
the IP address 75.98.169.138 .

**Comment by slrslr** [comment]
> You'd have to change your hosts file

`echo "75.98.169.138 download.lxcenter.org" >> /etc/hosts`

thank you, that worked. I assume adding this command to instalaltion script is not welcome..
